project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "course-materials/*.qmd"
    - "assignments.qmd"
    - "resources.qmd"
    - "install-guide.qmd"
    - "!downloadables/**"
  resources:
    - downloadables/**
    
website:
  title: "ESM 262"
  favicon: images/bren-hex.png
  navbar:
    right:
      - href: index.qmd
        text: home
      - text: syllabus
        href: ESM_262_syllabus.qmd
      - text: course materials
        menu:
          - text: week 1 (DD/MM)
            href: course-materials/week1.qmd
          - text: week 2 (DD/MM)
            href: course-materials/week2.qmd
      - text: assignments
        href: assignments.qmd
      - text: resources
        menu:
          - text: Recommended readings & resources
            href: resources.qmd
          - text: Installation guide
            href: install-guide.qmd
            target: _blank
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/UCSB-MEDS/EDS-website-template
          - text: Report a Bug
            url: https://github.com/UCSB-MEDS/EDS-website-template/issues
  page-footer:
    background: dark
    right: "[GitHub](https://github.com/UCSB-MEDS/EDS-website-template) and [Quarto](https://quarto.org/)"
    left: "This work is licensed under your preferred license"

format:
  html:
    theme: meds-website-styles.scss
    page-layout: full
    toc: true
    title-block-banner: true

