---
title: 'Documentation and Packages'
format:
  revealjs:
    theme: solarized
    resources: ["images"]
editor: visual
execute:
  echo: true
  warning: true
  message: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo =TRUE)
knitr::opts_chunk$set(error=TRUE)
#knitr::opts_knit$set(root.dir = '/Users/christina/Desktop/Courses.local/ESM262n/docs/packages')
library(tidyverse)
library(devtools)
library(roxygen2)
library(testthat)
library(here)


```

## [Goals for today]{style="color:orange"} {.scrollable}

- learn about creating packages in R
- learn about documenting your code in R
- practice sharing code with others with *git*

## [PACKAGES from Git]{style="color:orange"} {.scrollable}

- **Package**: An extension of the R base system with functions, data and documentation in standardized format.
- **Library**: A directory containing installed packages.
- **Repository**: A website providing packages for installation.
- **Source**: The original version of a package with human-readable text and code.
- **Binary**: A compiled version of a package with computer-readable text and code, may work only on a specific platform.
- **Base packages**: Part of the R source tree, maintained by R Core.
- **Recommended packages**: Part of every R installation, but not necessarily maintained by R Core.
- **Contributed packages**: All the rest. This does not mean that these packages are necessarily of lesser quality than the above, e.g., many contributed packages on CRAN are written and maintained by R Core members. They simply try to keep the base distribution as lean as possible.
- **User packages**: Packages that you write, share with a smaller community - not downloadable from CRAN, but can be downloaded (or sent as a zip file) and loaded into R

## [Installing packages from GitHub]{style="color:orange"} {.scrollable}

- you can transfer packages as a *tar* and *zipped* files, but most packages are now on git, so we can use devtools::install_github

you can install user packages from *github* - you need the *devtools* library to do this

install_github("naomitague/rainbow")

*Important* this doesn't create a *repo* of rainbow inside you working repository - so its safe! But you can't modify it

## [Write your own packages]{style="color:orange"} {.scrollable}

- to easily share functions and data with others with R-specific documentation

- have a set of tools (functions) that you often use, that can be easily loaded

- be part of the R community

- to share your work with others - you can make it available on GitHub,

- submit it to CRAN (the R package repository) - this is a great way to share your work and get feedback from others

[More about R-packages](https://r-pkgs.org/index.html)

## [Workflow for creating your own package]{style="color:orange"} {.scrollable}

- Create a new project in RStudio - select "New Project" and then "New Directory" and then "R Package"

- alternatively you can create a new package using the *usethis* package - this is a great way to create a new package and it will set up the structure for you

  - syntax is *usethis::create_package("path/to/your/package")* - this will create a new package in the specified directory

## [What happens]{style="color:orange"} {.scrollable}

- Creating a package will create a new directory with the following structure:

- *DESCRIPTION* - a file that contains metadata about your package (name, version, author, etc.)

- *NAMESPACE* - a file that contains information about the functions and data that are exported

- *R/* - a directory that contains the R code for your package (functions, data, etc)

- *man/* - a directory that contains the help files for your package (this is where the documentation generated by roxygen2 will go)

You can also add other directories for data, tests, vignettes, etc. but these are the basic ones you need to get started

- *Data* - a directory that contains data sets that are included in your package
- *tests* - a directory that contains tests for your package
- *vignettes* - a directory that contains long-form documentation for your package

## [Try it]{style="color:orange"} {.scrollable}

We will go through together

## [Adding your assignment files to a package]{style="color:orange"} {.scrollable}

- if you've already created an R subdirectory for Assignment 5 we can build a package around that

  - here I'd recommend `usethis::create_package(".")` from inside your existing project directory

- *important* all R files must be in the R subdirectory — scripts with loose code or `library()` calls outside functions will need to be cleaned up first

- alternatively you can start *fresh* and make a package in a new directory and then copy your R files into the R subdirectory of your package

  - here I'd recommend starting in a clean directory and create a project with a new git repo

## [Documentation]{style="color:orange"} {.scrollable}

- There is a standard format for documentation that can be read by automated tools (**Doxygen**)

- **roxygen2** - an R package that generates "standard" R documentation (help pages) using Doxygen-style syntax

- Automated documentation tools encourage a structured, consistent approach to documenting your code

- We will use the conventions that work with roxygen2 - and then use this program to generate formal R documentation. Roxygen2 is similar to Doxygen which is used for C code — so it’s a widely used format

## [Documentation in R with Roxygen]{style="color:orange"} {.scrollable}

Documentation is placed at the top of the *something.R* file; all lines start with *\#'*

See compute_NPV.R for an example

## [Three Parts to R documentation]{style="color:orange"} {.scrollable}

- **Description** - summary of what your function does
- **Tagged (using special “key” words)**

Here are some common examples — there are many others:

- *\@param* input/parameter description
- *\@return* what your function returns (outputs)
- *\@example* how to use it
- *\@references* citations or URLs
- *\@author* YOU

(You don’t need all of these. Start with at least `@param` and `@return`; `@examples` is also a good idea.)

- **Within function** Any use of \# within the body of the function (this does not get used in the Help)

## [Creating Help pages]{style="color:orange"} {.scrollable}

Once your roxygen comments are in place, generate help pages in one of two ways:

- `roxygenise()` from the roxygen2 package

- `document()` from the devtools package

- Both work on the \*.R files in the R directory of your project

- so you can have many functions in many files and they will all be documented at once

## [Workflow for documentation]{style="color:orange"} {.scrollable}

- Save your function, make sure that it is in the *R/* subdirectory your project directory eg *R/compute_NPV.R*

- Set your working directory to your project directory

- Make sure you've run `library(devtools)`

- Run `document()` from the RStudio menu or *document()* from command line - this will create documentation for all \*.R files you have in the R directory (you can have many of them)

- try `help(functionname)` to see the results

## [Try it]{style="color:orange"} {.scrollable}

- Add your functions from your Assignment 5 to the R subdirectory of your package

- Add documentation to one of the functions you built for Assignment 5

- Check that it works by running `help(functionname)`

- If you created a new project directory (started fresh) - you'll have to also make a new github repo

  - remember (usethis::use_github() will do this for you)

## [Pair and Share]{style="color:orange"} {.scrollable}

- find a new partner - give them the link to one of the functions that you've developed
- let them download from git
- see if they can create data and run the function just by reading the documentation
